version: "3"
services:
  widget:
    build: .
    ports:
      - "8080:80" # Expose the container’s port 80 to port 8080 on your local machine
    networks:
      - local-network
    restart: unless-stopped

networks:
  local-network:
    driver: bridge
